{% set supply_node_ip = salt['mine.get']('localhost*.' + salt['grains.get']('circle') + '.*', 'network.ip_addrs').items()[0][1][0] %}

# We only need the production database since it's the production server
# and we will get early failures if we forget to set the RAILS_ENV to
# production.

common: &common
  adapter: mysql
  database: {{ pillar['rails-app']['name'] }}_production
  username: app
  password: {{ pillar['mysql']['server']['root_password'] }}
  host: {{ supply_node_ip }}
  port: 3306

production:
  <<: *common
staging:
  <<: *common
staging1:
  <<: *common
staging2:
  <<: *common
east:
  <<: *common
west:
  <<: *common
dev:
  <<: *common
live:
  <<: *common
